// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/raft.proto

package com.xbb.javakv.connect.peer.message;

public interface EntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xbb.javakv.connect.peer.message.Entry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.xbb.javakv.connect.peer.message.EntryType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.xbb.javakv.connect.peer.message.EntryType type = 1;</code>
   */
  com.xbb.javakv.connect.peer.message.EntryType getType();

  /**
   * <code>uint64 term = 2;</code>
   */
  long getTerm();

  /**
   * <code>uint64 index = 3;</code>
   */
  long getIndex();

  /**
   * <code>bytes data = 4;</code>
   */
  com.google.protobuf.ByteString getData();
}
