// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/raft.proto

package com.xbb.javakv.connect.peer.message;

/**
 * Protobuf type {@code com.xbb.javakv.connect.peer.message.Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xbb.javakv.connect.peer.message.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    type_ = 0;
    to_ = 0L;
    from_ = 0L;
    term_ = 0L;
    logTerm_ = 0L;
    logIndex_ = 0L;
    entries_ = java.util.Collections.emptyList();
    result_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 16: {

            to_ = input.readUInt64();
            break;
          }
          case 24: {

            from_ = input.readUInt64();
            break;
          }
          case 32: {

            term_ = input.readUInt64();
            break;
          }
          case 40: {

            logTerm_ = input.readUInt64();
            break;
          }
          case 48: {

            logIndex_ = input.readUInt64();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              entries_ = new java.util.ArrayList<com.xbb.javakv.connect.peer.message.Entry>();
              mutable_bitField0_ |= 0x00000040;
            }
            entries_.add(
                input.readMessage(com.xbb.javakv.connect.peer.message.Entry.parser(), extensionRegistry));
            break;
          }
          case 64: {

            result_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        entries_ = java.util.Collections.unmodifiableList(entries_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xbb.javakv.connect.peer.message.RaftProto.internal_static_com_xbb_javakv_connect_peer_message_Message_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xbb.javakv.connect.peer.message.RaftProto.internal_static_com_xbb_javakv_connect_peer_message_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xbb.javakv.connect.peer.message.Message.class, com.xbb.javakv.connect.peer.message.Message.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.com.xbb.javakv.connect.peer.message.MessageType type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.com.xbb.javakv.connect.peer.message.MessageType type = 1;</code>
   */
  public com.xbb.javakv.connect.peer.message.MessageType getType() {
    com.xbb.javakv.connect.peer.message.MessageType result = com.xbb.javakv.connect.peer.message.MessageType.valueOf(type_);
    return result == null ? com.xbb.javakv.connect.peer.message.MessageType.UNRECOGNIZED : result;
  }

  public static final int TO_FIELD_NUMBER = 2;
  private long to_;
  /**
   * <code>uint64 to = 2;</code>
   */
  public long getTo() {
    return to_;
  }

  public static final int FROM_FIELD_NUMBER = 3;
  private long from_;
  /**
   * <code>uint64 from = 3;</code>
   */
  public long getFrom() {
    return from_;
  }

  public static final int TERM_FIELD_NUMBER = 4;
  private long term_;
  /**
   * <code>uint64 term = 4;</code>
   */
  public long getTerm() {
    return term_;
  }

  public static final int LOGTERM_FIELD_NUMBER = 5;
  private long logTerm_;
  /**
   * <code>uint64 logTerm = 5;</code>
   */
  public long getLogTerm() {
    return logTerm_;
  }

  public static final int LOGINDEX_FIELD_NUMBER = 6;
  private long logIndex_;
  /**
   * <code>uint64 logIndex = 6;</code>
   */
  public long getLogIndex() {
    return logIndex_;
  }

  public static final int ENTRIES_FIELD_NUMBER = 7;
  private java.util.List<com.xbb.javakv.connect.peer.message.Entry> entries_;
  /**
   * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
   */
  public java.util.List<com.xbb.javakv.connect.peer.message.Entry> getEntriesList() {
    return entries_;
  }
  /**
   * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
   */
  public java.util.List<? extends com.xbb.javakv.connect.peer.message.EntryOrBuilder>
      getEntriesOrBuilderList() {
    return entries_;
  }
  /**
   * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
   */
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
   */
  public com.xbb.javakv.connect.peer.message.Entry getEntries(int index) {
    return entries_.get(index);
  }
  /**
   * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
   */
  public com.xbb.javakv.connect.peer.message.EntryOrBuilder getEntriesOrBuilder(
      int index) {
    return entries_.get(index);
  }

  public static final int RESULT_FIELD_NUMBER = 8;
  private boolean result_;
  /**
   * <code>bool result = 8;</code>
   */
  public boolean getResult() {
    return result_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.xbb.javakv.connect.peer.message.MessageType.MsgEntries.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (to_ != 0L) {
      output.writeUInt64(2, to_);
    }
    if (from_ != 0L) {
      output.writeUInt64(3, from_);
    }
    if (term_ != 0L) {
      output.writeUInt64(4, term_);
    }
    if (logTerm_ != 0L) {
      output.writeUInt64(5, logTerm_);
    }
    if (logIndex_ != 0L) {
      output.writeUInt64(6, logIndex_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      output.writeMessage(7, entries_.get(i));
    }
    if (result_ != false) {
      output.writeBool(8, result_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.xbb.javakv.connect.peer.message.MessageType.MsgEntries.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (to_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, to_);
    }
    if (from_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, from_);
    }
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, term_);
    }
    if (logTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, logTerm_);
    }
    if (logIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, logIndex_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, entries_.get(i));
    }
    if (result_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, result_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xbb.javakv.connect.peer.message.Message)) {
      return super.equals(obj);
    }
    com.xbb.javakv.connect.peer.message.Message other = (com.xbb.javakv.connect.peer.message.Message) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && (getTo()
        == other.getTo());
    result = result && (getFrom()
        == other.getFrom());
    result = result && (getTerm()
        == other.getTerm());
    result = result && (getLogTerm()
        == other.getLogTerm());
    result = result && (getLogIndex()
        == other.getLogIndex());
    result = result && getEntriesList()
        .equals(other.getEntriesList());
    result = result && (getResult()
        == other.getResult());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + TO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTo());
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFrom());
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    hash = (37 * hash) + LOGTERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLogTerm());
    hash = (37 * hash) + LOGINDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLogIndex());
    if (getEntriesCount() > 0) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntriesList().hashCode();
    }
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getResult());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xbb.javakv.connect.peer.message.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xbb.javakv.connect.peer.message.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xbb.javakv.connect.peer.message.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xbb.javakv.connect.peer.message.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xbb.javakv.connect.peer.message.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xbb.javakv.connect.peer.message.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xbb.javakv.connect.peer.message.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xbb.javakv.connect.peer.message.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xbb.javakv.connect.peer.message.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xbb.javakv.connect.peer.message.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xbb.javakv.connect.peer.message.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xbb.javakv.connect.peer.message.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xbb.javakv.connect.peer.message.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xbb.javakv.connect.peer.message.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xbb.javakv.connect.peer.message.Message)
      com.xbb.javakv.connect.peer.message.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xbb.javakv.connect.peer.message.RaftProto.internal_static_com_xbb_javakv_connect_peer_message_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xbb.javakv.connect.peer.message.RaftProto.internal_static_com_xbb_javakv_connect_peer_message_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xbb.javakv.connect.peer.message.Message.class, com.xbb.javakv.connect.peer.message.Message.Builder.class);
    }

    // Construct using com.xbb.javakv.connect.peer.message.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEntriesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      to_ = 0L;

      from_ = 0L;

      term_ = 0L;

      logTerm_ = 0L;

      logIndex_ = 0L;

      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        entriesBuilder_.clear();
      }
      result_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xbb.javakv.connect.peer.message.RaftProto.internal_static_com_xbb_javakv_connect_peer_message_Message_descriptor;
    }

    public com.xbb.javakv.connect.peer.message.Message getDefaultInstanceForType() {
      return com.xbb.javakv.connect.peer.message.Message.getDefaultInstance();
    }

    public com.xbb.javakv.connect.peer.message.Message build() {
      com.xbb.javakv.connect.peer.message.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.xbb.javakv.connect.peer.message.Message buildPartial() {
      com.xbb.javakv.connect.peer.message.Message result = new com.xbb.javakv.connect.peer.message.Message(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.type_ = type_;
      result.to_ = to_;
      result.from_ = from_;
      result.term_ = term_;
      result.logTerm_ = logTerm_;
      result.logIndex_ = logIndex_;
      if (entriesBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.entries_ = entries_;
      } else {
        result.entries_ = entriesBuilder_.build();
      }
      result.result_ = result_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xbb.javakv.connect.peer.message.Message) {
        return mergeFrom((com.xbb.javakv.connect.peer.message.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xbb.javakv.connect.peer.message.Message other) {
      if (other == com.xbb.javakv.connect.peer.message.Message.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getTo() != 0L) {
        setTo(other.getTo());
      }
      if (other.getFrom() != 0L) {
        setFrom(other.getFrom());
      }
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (other.getLogTerm() != 0L) {
        setLogTerm(other.getLogTerm());
      }
      if (other.getLogIndex() != 0L) {
        setLogIndex(other.getLogIndex());
      }
      if (entriesBuilder_ == null) {
        if (!other.entries_.isEmpty()) {
          if (entries_.isEmpty()) {
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureEntriesIsMutable();
            entries_.addAll(other.entries_);
          }
          onChanged();
        }
      } else {
        if (!other.entries_.isEmpty()) {
          if (entriesBuilder_.isEmpty()) {
            entriesBuilder_.dispose();
            entriesBuilder_ = null;
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000040);
            entriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntriesFieldBuilder() : null;
          } else {
            entriesBuilder_.addAllMessages(other.entries_);
          }
        }
      }
      if (other.getResult() != false) {
        setResult(other.getResult());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xbb.javakv.connect.peer.message.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xbb.javakv.connect.peer.message.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.com.xbb.javakv.connect.peer.message.MessageType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.xbb.javakv.connect.peer.message.MessageType type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.xbb.javakv.connect.peer.message.MessageType type = 1;</code>
     */
    public com.xbb.javakv.connect.peer.message.MessageType getType() {
      com.xbb.javakv.connect.peer.message.MessageType result = com.xbb.javakv.connect.peer.message.MessageType.valueOf(type_);
      return result == null ? com.xbb.javakv.connect.peer.message.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.xbb.javakv.connect.peer.message.MessageType type = 1;</code>
     */
    public Builder setType(com.xbb.javakv.connect.peer.message.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.xbb.javakv.connect.peer.message.MessageType type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private long to_ ;
    /**
     * <code>uint64 to = 2;</code>
     */
    public long getTo() {
      return to_;
    }
    /**
     * <code>uint64 to = 2;</code>
     */
    public Builder setTo(long value) {
      
      to_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 to = 2;</code>
     */
    public Builder clearTo() {
      
      to_ = 0L;
      onChanged();
      return this;
    }

    private long from_ ;
    /**
     * <code>uint64 from = 3;</code>
     */
    public long getFrom() {
      return from_;
    }
    /**
     * <code>uint64 from = 3;</code>
     */
    public Builder setFrom(long value) {
      
      from_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 from = 3;</code>
     */
    public Builder clearFrom() {
      
      from_ = 0L;
      onChanged();
      return this;
    }

    private long term_ ;
    /**
     * <code>uint64 term = 4;</code>
     */
    public long getTerm() {
      return term_;
    }
    /**
     * <code>uint64 term = 4;</code>
     */
    public Builder setTerm(long value) {
      
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 term = 4;</code>
     */
    public Builder clearTerm() {
      
      term_ = 0L;
      onChanged();
      return this;
    }

    private long logTerm_ ;
    /**
     * <code>uint64 logTerm = 5;</code>
     */
    public long getLogTerm() {
      return logTerm_;
    }
    /**
     * <code>uint64 logTerm = 5;</code>
     */
    public Builder setLogTerm(long value) {
      
      logTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 logTerm = 5;</code>
     */
    public Builder clearLogTerm() {
      
      logTerm_ = 0L;
      onChanged();
      return this;
    }

    private long logIndex_ ;
    /**
     * <code>uint64 logIndex = 6;</code>
     */
    public long getLogIndex() {
      return logIndex_;
    }
    /**
     * <code>uint64 logIndex = 6;</code>
     */
    public Builder setLogIndex(long value) {
      
      logIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 logIndex = 6;</code>
     */
    public Builder clearLogIndex() {
      
      logIndex_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.xbb.javakv.connect.peer.message.Entry> entries_ =
      java.util.Collections.emptyList();
    private void ensureEntriesIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        entries_ = new java.util.ArrayList<com.xbb.javakv.connect.peer.message.Entry>(entries_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xbb.javakv.connect.peer.message.Entry, com.xbb.javakv.connect.peer.message.Entry.Builder, com.xbb.javakv.connect.peer.message.EntryOrBuilder> entriesBuilder_;

    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public java.util.List<com.xbb.javakv.connect.peer.message.Entry> getEntriesList() {
      if (entriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entries_);
      } else {
        return entriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public int getEntriesCount() {
      if (entriesBuilder_ == null) {
        return entries_.size();
      } else {
        return entriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public com.xbb.javakv.connect.peer.message.Entry getEntries(int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);
      } else {
        return entriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public Builder setEntries(
        int index, com.xbb.javakv.connect.peer.message.Entry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.set(index, value);
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public Builder setEntries(
        int index, com.xbb.javakv.connect.peer.message.Entry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.set(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public Builder addEntries(com.xbb.javakv.connect.peer.message.Entry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public Builder addEntries(
        int index, com.xbb.javakv.connect.peer.message.Entry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(index, value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public Builder addEntries(
        com.xbb.javakv.connect.peer.message.Entry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public Builder addEntries(
        int index, com.xbb.javakv.connect.peer.message.Entry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public Builder addAllEntries(
        java.lang.Iterable<? extends com.xbb.javakv.connect.peer.message.Entry> values) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entries_);
        onChanged();
      } else {
        entriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public Builder clearEntries() {
      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        entriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public Builder removeEntries(int index) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.remove(index);
        onChanged();
      } else {
        entriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public com.xbb.javakv.connect.peer.message.Entry.Builder getEntriesBuilder(
        int index) {
      return getEntriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public com.xbb.javakv.connect.peer.message.EntryOrBuilder getEntriesOrBuilder(
        int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);  } else {
        return entriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public java.util.List<? extends com.xbb.javakv.connect.peer.message.EntryOrBuilder>
         getEntriesOrBuilderList() {
      if (entriesBuilder_ != null) {
        return entriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entries_);
      }
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public com.xbb.javakv.connect.peer.message.Entry.Builder addEntriesBuilder() {
      return getEntriesFieldBuilder().addBuilder(
          com.xbb.javakv.connect.peer.message.Entry.getDefaultInstance());
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public com.xbb.javakv.connect.peer.message.Entry.Builder addEntriesBuilder(
        int index) {
      return getEntriesFieldBuilder().addBuilder(
          index, com.xbb.javakv.connect.peer.message.Entry.getDefaultInstance());
    }
    /**
     * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
     */
    public java.util.List<com.xbb.javakv.connect.peer.message.Entry.Builder>
         getEntriesBuilderList() {
      return getEntriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xbb.javakv.connect.peer.message.Entry, com.xbb.javakv.connect.peer.message.Entry.Builder, com.xbb.javakv.connect.peer.message.EntryOrBuilder>
        getEntriesFieldBuilder() {
      if (entriesBuilder_ == null) {
        entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xbb.javakv.connect.peer.message.Entry, com.xbb.javakv.connect.peer.message.Entry.Builder, com.xbb.javakv.connect.peer.message.EntryOrBuilder>(
                entries_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        entries_ = null;
      }
      return entriesBuilder_;
    }

    private boolean result_ ;
    /**
     * <code>bool result = 8;</code>
     */
    public boolean getResult() {
      return result_;
    }
    /**
     * <code>bool result = 8;</code>
     */
    public Builder setResult(boolean value) {
      
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool result = 8;</code>
     */
    public Builder clearResult() {
      
      result_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xbb.javakv.connect.peer.message.Message)
  }

  // @@protoc_insertion_point(class_scope:com.xbb.javakv.connect.peer.message.Message)
  private static final com.xbb.javakv.connect.peer.message.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xbb.javakv.connect.peer.message.Message();
  }

  public static com.xbb.javakv.connect.peer.message.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  public com.xbb.javakv.connect.peer.message.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

