// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/raft.proto

package com.xbb.javakv.connect.peer.message;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xbb.javakv.connect.peer.message.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.xbb.javakv.connect.peer.message.MessageType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.xbb.javakv.connect.peer.message.MessageType type = 1;</code>
   */
  com.xbb.javakv.connect.peer.message.MessageType getType();

  /**
   * <code>uint64 to = 2;</code>
   */
  long getTo();

  /**
   * <code>uint64 from = 3;</code>
   */
  long getFrom();

  /**
   * <code>uint64 term = 4;</code>
   */
  long getTerm();

  /**
   * <code>uint64 logTerm = 5;</code>
   */
  long getLogTerm();

  /**
   * <code>uint64 logIndex = 6;</code>
   */
  long getLogIndex();

  /**
   * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
   */
  java.util.List<com.xbb.javakv.connect.peer.message.Entry>
      getEntriesList();
  /**
   * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
   */
  com.xbb.javakv.connect.peer.message.Entry getEntries(int index);
  /**
   * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
   */
  java.util.List<? extends com.xbb.javakv.connect.peer.message.EntryOrBuilder>
      getEntriesOrBuilderList();
  /**
   * <code>repeated .com.xbb.javakv.connect.peer.message.Entry entries = 7;</code>
   */
  com.xbb.javakv.connect.peer.message.EntryOrBuilder getEntriesOrBuilder(
      int index);

  /**
   * <code>bool result = 8;</code>
   */
  boolean getResult();
}
