// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/raft.proto

package com.xbb.javakv.connect.peer.message;

/**
 * Protobuf enum {@code com.xbb.javakv.connect.peer.message.MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MsgEntries = 0;</code>
   */
  MsgEntries(0),
  /**
   * <code>MsgEntriesResp = 1;</code>
   */
  MsgEntriesResp(1),
  /**
   * <code>MsgHeartbeat = 2;</code>
   */
  MsgHeartbeat(2),
  /**
   * <code>MsgHeartbeatResp = 3;</code>
   */
  MsgHeartbeatResp(3),
  /**
   * <code>MsgVote = 4;</code>
   */
  MsgVote(4),
  /**
   * <code>MsgVoteResp = 5;</code>
   */
  MsgVoteResp(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MsgEntries = 0;</code>
   */
  public static final int MsgEntries_VALUE = 0;
  /**
   * <code>MsgEntriesResp = 1;</code>
   */
  public static final int MsgEntriesResp_VALUE = 1;
  /**
   * <code>MsgHeartbeat = 2;</code>
   */
  public static final int MsgHeartbeat_VALUE = 2;
  /**
   * <code>MsgHeartbeatResp = 3;</code>
   */
  public static final int MsgHeartbeatResp_VALUE = 3;
  /**
   * <code>MsgVote = 4;</code>
   */
  public static final int MsgVote_VALUE = 4;
  /**
   * <code>MsgVoteResp = 5;</code>
   */
  public static final int MsgVoteResp_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return MsgEntries;
      case 1: return MsgEntriesResp;
      case 2: return MsgHeartbeat;
      case 3: return MsgHeartbeatResp;
      case 4: return MsgVote;
      case 5: return MsgVoteResp;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.xbb.javakv.connect.peer.message.RaftProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.xbb.javakv.connect.peer.message.MessageType)
}

