// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/raft.proto

package com.xbb.javakv.connect.peer.message;

public final class RaftProto {
  private RaftProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xbb_javakv_connect_peer_message_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xbb_javakv_connect_peer_message_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xbb_javakv_connect_peer_message_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xbb_javakv_connect_peer_message_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/resources/raft.proto\022#com.xbb" +
      ".com.xbb.javakv.connect.peer.message\"p\n\005Entry\022<\n" +
      "\004type\030\001 \001(\0162..javakv.connect.pee" +
      "r.message.EntryType\022\014\n\004term\030\002 \001(\004\022\r\n\005ind" +
      "ex\030\003 \001(\004\022\014\n\004data\030\004 \001(\014\"\341\001\n\007Message\022>\n\004ty" +
      "pe\030\001 \001(\01620.com.xbb.javakv.connect.peer.m" +
      "essage.MessageType\022\n\n\002to\030\002 \001(\004\022\014\n\004from\030\003" +
      " \001(\004\022\014\n\004term\030\004 \001(\004\022\017\n\007logTerm\030\005 \001(\004\022\020\n\010l" +
      "ogIndex\030\006 \001(\004\022;\n\007entries\030\007 \003(\0132*.com.xbb" +
      ".com.xbb.javakv.connect.peer.message.Entry\022\016\n\006re" +
      "sult\030\010 \001(\010*1\n\tEntryType\022\017\n\013EntryNormal\020\000" +
      "\022\023\n\017EntryConfChange\020\001*w\n\013MessageType\022\016\n\n" +
      "MsgEntries\020\000\022\022\n\016MsgEntriesResp\020\001\022\020\n\014MsgH" +
      "eartbeat\020\002\022\024\n\020MsgHeartbeatResp\020\003\022\013\n\007MsgV" +
      "ote\020\004\022\017\n\013MsgVoteResp\020\005B7\n#javakv" +
      ".connect.peer.messageB\tRaftProtoH\001P\001\210\001\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xbb_javakv_connect_peer_message_Entry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xbb_javakv_connect_peer_message_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xbb_javakv_connect_peer_message_Entry_descriptor,
        new java.lang.String[] { "Type", "Term", "Index", "Data", });
    internal_static_com_xbb_javakv_connect_peer_message_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xbb_javakv_connect_peer_message_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xbb_javakv_connect_peer_message_Message_descriptor,
        new java.lang.String[] { "Type", "To", "From", "Term", "LogTerm", "LogIndex", "Entries", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
